name: procaselfield
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  geolocator: ^11.0.0
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  path: ^1.9.0
  maplibre_gl: ^0.16.0

flutter:
  uses-material-design: true
  assets:
    - assets/schema.sql
